/*
const mapNames = [
  ...new Set(
    [...document.querySelectorAll('.MapCardComponentStyle-message span')]
      .map(el => el.textContent.trim())
      .map(name =>
        name
          .replace(/ REMASTER XS MM$/, '')
          .replace(/ REMASTER MM$/, '')
          .replace(/ MM$/, '')
      )
  )
];

console.log(mapNames);
*/

const mapsEn = [
    "Aleksandrovsk",
    "Archipelago",
    "Arena",
    "Atra",
    "Barda",
    "Berlin",
    "Bobruisk",
    "Boombox",
    "Brest",
    "Bridges",
    "Camp",
    "Canyon",
    "Chernobyl",
    "Chernushka",
    "Cologne",
    "Combe",
    "Courage",
    "Cross",
    "Deathtrack",
    "Deck 9",
    "Desert",
    "Duality",
    "Duel",
    "Dusseldorf",
    "Edinburgh",
    "Esplanade",
    "Factory",
    "Farm",
    "Forest",
    "Fort Knox",
    "Future",
    "Garder",
    "Gravity",
    "Gubakha",
    "Highland",
    "Highways",
    "Hill",
    "Industrial Zone",
    "Iran",
    "Island",
    "Kolhoz",
    "Kungur",
    "Lost Temple",
    "Madness",
    "Madness 2",
    "Magadan",
    "Magistral",
    "Massacre",
    "Molotov",
    "Monte Carlo",
    "Noise",
    "Novel",
    "Opposition",
    "Osa",
    "Parma",
    "Pass",
    "Ping-Pong",
    "Polygon",
    "Red Alert",
    "Rift",
    "Rio",
    "Sandal",
    "Sandbox",
    "Scope",
    "Serpuhov",
    "Short bridge",
    "Siege",
    "Silence",
    "Skylark",
    "Skyscrapers",
    "Solikamsk",
    "Stadium",
    "Station",
    "Subway",
    "Tribute",
    "Valley",
    "Wave",
    "Wolfenstein",
    "Year 2042",
    "Yorkshire",
    "Zone"
]

const mapsRu = [
    "Александровск",
    "Арена",
    "Архипелаг",
    "Атра",
    "Барда",
    "Безумие",
    "Безумие 2",
    "Берлин",
    "Бобруйск",
    "Бойня",
    "Брест",
    "Будущее",
    "Бумбокс",
    "Волна",
    "Вольфенштейн",
    "Гардер",
    "Год 2042",
    "Гравити",
    "Губаха",
    "Долина",
    "Дуалити",
    "Дуэль",
    "Дюссельдорф",
    "Жаворонки",
    "Зона",
    "Иран",
    "Йоркшир",
    "Каньон",
    "Колхоз",
    "Кунгур",
    "Кураж",
    "Кёльн",
    "Лагерь",
    "Магадан",
    "Магистраль",
    "Молотов",
    "Монте-Карло",
    "Мостик",
    "Мосты",
    "Небоскрёбы",
    "Новэл",
    "Овраг",
    "Оса",
    "Осада",
    "Остров",
    "Палуба 9",
    "Парма",
    "Перевал",
    "Перекрёсток",
    "Песочница",
    "Пинг-Понг",
    "Плато",
    "Подземка",
    "Полигон",
    "Промзона",
    "Простор",
    "Противостояние",
    "Пустыня",
    "Ред Алерт",
    "Рио",
    "Сандал",
    "Серпухов",
    "Соликамск",
    "Стадион",
    "Станция",
    "Тишина",
    "Трек",
    "Трибьют",
    "Тэмпл",
    "Ущелье",
    "Фабрика",
    "Ферма",
    "Форест",
    "Форт Нокс",
    "Холм",
    "Чернобыль",
    "Чернушка",
    "Шоссе",
    "Шум",
    "Эдинбург",
    "Эспланада"
]

//  ------------------------------------------------------------------------- 

const maps = [
    { "en": "Aleksandrovsk", "ru": "Александровск" },
    { "en": "Archipelago", "ru": "Архипелаг" },
    { "en": "Arena", "ru": "Арена" },
    { "en": "Atra", "ru": "Атра" },
    { "en": "Barda", "ru": "Барда" },
    { "en": "Berlin", "ru": "Берлин" },
    { "en": "Bobruisk", "ru": "Бобруйск" },
    { "en": "Boombox", "ru": "Бумбокс" },
    { "en": "Brest", "ru": "Брест" },
    { "en": "Bridges", "ru": "Мосты" },
    { "en": "Camp", "ru": "Лагерь" },
    { "en": "Canyon", "ru": "Каньон" },
    { "en": "Chernobyl", "ru": "Чернобыль" },
    { "en": "Chernushka", "ru": "Чернушка" },
    { "en": "Cologne", "ru": "Кёльн" },
    { "en": "Combe", "ru": "Овраг" },
    { "en": "Courage", "ru": "Кураж" },
    { "en": "Cross", "ru": "Перекрёсток" },
    { "en": "Deathtrack", "ru": "Трек" },
    { "en": "Deck 9", "ru": "Палуба 9" },
    { "en": "Desert", "ru": "Пустыня" },
    { "en": "Duality", "ru": "Дуалити" },
    { "en": "Duel", "ru": "Дуэль" },
    { "en": "Dusseldorf", "ru": "Дюссельдорф" },
    { "en": "Edinburgh", "ru": "Эдинбург" },
    { "en": "Esplanade", "ru": "Эспланада" },
    { "en": "Factory", "ru": "Фабрика" },
    { "en": "Farm", "ru": "Ферма" },
    { "en": "Forest", "ru": "Форест" },
    { "en": "Fort Knox", "ru": "Форт Нокс" },
    { "en": "Future", "ru": "Будущее" },
    { "en": "Garder", "ru": "Гардер" },
    { "en": "Gravity", "ru": "Гравити" },
    { "en": "Gubakha", "ru": "Губаха" },
    { "en": "Highland", "ru": "Плато" },
    { "en": "Highways", "ru": "Шоссе" },
    { "en": "Hill", "ru": "Холм" },
    { "en": "Industrial Zone", "ru": "Промзона" },
    { "en": "Iran", "ru": "Иран" },
    { "en": "Island", "ru": "Остров" },
    { "en": "Kolhoz", "ru": "Колхоз" },
    { "en": "Kungur", "ru": "Кунгур" },
    { "en": "Lost Temple", "ru": "Тэмпл" },
    { "en": "Madness", "ru": "Безумие" },
    { "en": "Madness 2", "ru": "Безумие 2" },
    { "en": "Magadan", "ru": "Магадан" },
    { "en": "Magistral", "ru": "Магистраль" },
    { "en": "Massacre", "ru": "Бойня" },
    { "en": "Molotov", "ru": "Молотов" },
    { "en": "Monte Carlo", "ru": "Монте-Карло" },
    { "en": "Noise", "ru": "Шум" },
    { "en": "Novel", "ru": "Новэл" },
    { "en": "Opposition", "ru": "Противостояние" },
    { "en": "Osa", "ru": "Оса" },
    { "en": "Parma", "ru": "Парма" },
    { "en": "Pass", "ru": "Перевал" },
    { "en": "Ping-Pong", "ru": "Пинг-Понг" },
    { "en": "Polygon", "ru": "Полигон" },
    { "en": "Red Alert", "ru": "Ред Алерт" },
    { "en": "Rift", "ru": "Ущелье" },
    { "en": "Rio", "ru": "Рио" },
    { "en": "Sandal", "ru": "Сандал" },
    { "en": "Sandbox", "ru": "Песочница" },
    { "en": "Scope", "ru": "Простор" },
    { "en": "Serpuhov", "ru": "Серпухов" },
    { "en": "Short bridge", "ru": "Мостик" },
    { "en": "Siege", "ru": "Осада" },
    { "en": "Silence", "ru": "Тишина" },
    { "en": "Skylark", "ru": "Жаворонки" },
    { "en": "Skyscrapers", "ru": "Небоскрёбы" },
    { "en": "Solikamsk", "ru": "Соликамск" },
    { "en": "Stadium", "ru": "Стадион" },
    { "en": "Station", "ru": "Станция" },
    { "en": "Subway", "ru": "Подземка" },
    { "en": "Tribute", "ru": "Трибьют" },
    { "en": "Valley", "ru": "Долина" },
    { "en": "Wave", "ru": "Волна" },
    { "en": "Wolfenstein", "ru": "Вольфенштейн" },
    { "en": "Year 2042", "ru": "Год 2042" },
    { "en": "Yorkshire", "ru": "Йоркшир" },
    { "en": "Zone", "ru": "Зона" }
];